# Generated by Django 5.0.6 on 2024-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='details',
            field=models.TextField(default='default details', max_length=255),
            preserve_default=False,
        ),
    ]
