# Generated by Django 5.0.6 on 2024-05-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todo_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='complete',
        ),
    ]
